require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AchivementsController do

  # This should return the minimal set of attributes required to create a valid
  # Achivement. As you add validations to Achivement, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all achivements as @achivements" do
      achivement = Achivement.create! valid_attributes
      get :index
      assigns(:achivements).should eq([achivement])
    end
  end

  describe "GET show" do
    it "assigns the requested achivement as @achivement" do
      achivement = Achivement.create! valid_attributes
      get :show, :id => achivement.id.to_s
      assigns(:achivement).should eq(achivement)
    end
  end

  describe "GET new" do
    it "assigns a new achivement as @achivement" do
      get :new
      assigns(:achivement).should be_a_new(Achivement)
    end
  end

  describe "GET edit" do
    it "assigns the requested achivement as @achivement" do
      achivement = Achivement.create! valid_attributes
      get :edit, :id => achivement.id.to_s
      assigns(:achivement).should eq(achivement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Achivement" do
        expect {
          post :create, :achivement => valid_attributes
        }.to change(Achivement, :count).by(1)
      end

      it "assigns a newly created achivement as @achivement" do
        post :create, :achivement => valid_attributes
        assigns(:achivement).should be_a(Achivement)
        assigns(:achivement).should be_persisted
      end

      it "redirects to the created achivement" do
        post :create, :achivement => valid_attributes
        response.should redirect_to(Achivement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved achivement as @achivement" do
        # Trigger the behavior that occurs when invalid params are submitted
        Achivement.any_instance.stub(:save).and_return(false)
        post :create, :achivement => {}
        assigns(:achivement).should be_a_new(Achivement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Achivement.any_instance.stub(:save).and_return(false)
        post :create, :achivement => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested achivement" do
        achivement = Achivement.create! valid_attributes
        # Assuming there are no other achivements in the database, this
        # specifies that the Achivement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Achivement.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => achivement.id, :achivement => {'these' => 'params'}
      end

      it "assigns the requested achivement as @achivement" do
        achivement = Achivement.create! valid_attributes
        put :update, :id => achivement.id, :achivement => valid_attributes
        assigns(:achivement).should eq(achivement)
      end

      it "redirects to the achivement" do
        achivement = Achivement.create! valid_attributes
        put :update, :id => achivement.id, :achivement => valid_attributes
        response.should redirect_to(achivement)
      end
    end

    describe "with invalid params" do
      it "assigns the achivement as @achivement" do
        achivement = Achivement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Achivement.any_instance.stub(:save).and_return(false)
        put :update, :id => achivement.id.to_s, :achivement => {}
        assigns(:achivement).should eq(achivement)
      end

      it "re-renders the 'edit' template" do
        achivement = Achivement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Achivement.any_instance.stub(:save).and_return(false)
        put :update, :id => achivement.id.to_s, :achivement => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested achivement" do
      achivement = Achivement.create! valid_attributes
      expect {
        delete :destroy, :id => achivement.id.to_s
      }.to change(Achivement, :count).by(-1)
    end

    it "redirects to the achivements list" do
      achivement = Achivement.create! valid_attributes
      delete :destroy, :id => achivement.id.to_s
      response.should redirect_to(achivements_url)
    end
  end

end
